version: '3.8'

services:
  # API Server
  api:
    build: 
      context: ./src
      dockerfile: Dockerfile
    container_name: course-rag-api
    ports:
      - "8200:8200"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/.env:/app/.env:ro  # Mount environment file

  # Test Interface Server
  test-interface:
    build: 
      context: ./src
      dockerfile: Dockerfile
    container_name: course-rag-test
    ports:
      - "8280:8280"
    command: ["python", "tests/test_server.py", "--port", "8280"]
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - api

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: course-rag-nginx
    ports:
      - "90:90"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - test-interface
    restart: unless-stopped 