version: '3.8'

services:
  # API Server
  api:
    build: 
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/.env:/app/.env:ro  # Mount environment file

  # Test Interface Server
  test-interface:
    build: 
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: ["python", "tests/test_server.py", "--port", "8081"]
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - api

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - test-interface
    restart: unless-stopped
    profiles:
      - production 