version: '3.8'

services:
  api:
    build: ./src
    container_name: course-rag-api
    ports:
      - "8200:8200"
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - course-rag-network

  test-interface:
    build: ./src
    container_name: course-rag-test
    ports:
      - "8281:8281"
    command: python tests/test_server.py --port 8281
    depends_on:
      - api
    networks:
      - course-rag-network

  nginx:
    image: nginx:alpine
    container_name: course-rag-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - test-interface
    networks:
      - course-rag-network

networks:
  course-rag-network:
    driver: bridge 