services:
  api:
    build: ./src
    container_name: course-rag-api
    ports:
      - "8200:8200"
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - course-rag-network

  test-interface:
    build: ./src
    container_name: course-rag-test
    ports:
      - "8280:8280"
    command: python tests/test_server.py --port 8280
    depends_on:
      api:
        condition: service_healthy
    networks:
      - course-rag-network

  nginx:
    image: nginx:alpine
    container_name: course-rag-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      api:
        condition: service_healthy
      test-interface:
        condition: service_started
    networks:
      - course-rag-network

networks:
  course-rag-network:
    driver: bridge 